#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            	0 #2
bspc config window_gap        	    	0 #12

bspc config split_ratio             	0.52
bspc config borderless_monocle      	true
bspc config gapless_monocle         	true

# mouse se centra en el medio del focus
bspc config pointer_follows_focus   	false
# focus_follows_pointer sets whether the mouse pointer can control which window gets focus.
bspc config focus_follows_pointer	true

# automatic_scheme determines the layout of the windows when split in automatic mode
bspc config automatic_scheme	    spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1

# inicio de daemon de emacs
/usr/bin/emacs --daemon
